config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions", invitations: "invitations"}
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  root 'homes#index'
  resources :homes
  resources :events
  namespace :superadmin do
    resources :event_types
    resources :events ,:only=>[:index ,:destroy]
    resources :clients do
      delete :remove_brand
      get :impersonate
      resources :users do
        get :resend_invitation
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :groups
    resources :events
    resources :brands
  end
  namespace :admin do
    get '/login_as_master' => 'admin_application#login_as_master'
    resources :dashboard do
      collection do
        get "images"
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :events do
      resources :user_events do
        delete :delete_image
      end
    end
    resources :groups
    resources :clients do
      collection do
        get :reps_and_groups
      end
    end
  end
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :contacts
      resources :events do
        collection do
          get :active
          get :expired
        end
      end
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :client
  belongs_to :group
  belongs_to :brand
  has_one :address, class_name: 'Location'
  belongs_to :creator, class_name: 'User', :foreign_key => 'user_id'
  has_many :user_events
  belongs_to :event_type
  has_many :users, :through => :user_events
  accepts_nested_attributes_for :address, reject_if: :all_blank, allow_destroy: true

  enum promo_category: [:promo_rep, :promo_group]

  def self.active
    self.where(deleted: false)
  end

  def self.active_events
    self.where('(end_time NOTNULL AND end_time > ?)', Time.now- 1.hour)
        .where(:user_events => {:status => UserEvent::statuses[:accepted], :check_out => nil})
  end


  def self.checkedin_events
    self.where('(end_time NOTNULL AND end_time > ?)', Time.now)
        .where(:user_events => {:status => UserEvent::statuses[:accepted], :check_out => nil}).where.not(:user_events => {:check_in => nil})
  end

  def self.expired_events
    self.where('(end_time NOTNULL AND end_time < ?)', Time.now)
        .where(:user_events => {:status => UserEvent::statuses[:accepted], :check_out => nil}).where.not(:user_events => {:check_in => nil})
  end

  SORT_BY =
      {
          # 'Date (dsc)' => 'nd',
          # 'Date (asc)' => 'na',
          'Type (asc)' => 'ta',
          'Type (dsc)' => 'td',
          'Area (asc)' => 'aa',
          'Area (dsc)' => 'ad',
      }

  def self.order_events(sort)
    if sort.nil? or sort=='nd'
      order(start_time: :desc)
    elsif sort=='na'
      order(start_time: :asc)
    elsif sort=='td'
      order('event_types.name DESC')
    elsif sort=='ta'
      order('event_types.name ASC')
    elsif sort=='aa'
      order(area: :asc)
    elsif sort=='ad'
      order(area: :desc)
    end
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events
end

app/controllers/admin/events_controller.rb
require 'platform/email_helper'
class Admin::EventsController < Admin::AdminApplicationController
  include EmailHelper

  def index
    if params[:search]
      unless params[:promo_id].blank?
        if params[:search_type]=='promo_group'
          @events=@current_client.events.active.where(:group_id => params[:promo_id]).order('updated_at desc').collect { |u| u }
        elsif params[:search_type]=='promo_rep'
          @events=@current_client.events.active.joins(:users).where("users.id IN (?)", params[:promo_id]).order('updated_at desc').collect { |u| u }
        end
        unless @events.kind_of?(Array)
          @events = @events.page(params[:page]).per(10)
        else
          @events = Kaminari.paginate_array(@events.uniq).page(params[:page]).per(10)
        end
      end
    else
      @events=@current_client.events.active.page(params[:page]).per(20).order('updated_at desc')
    end
    respond_to do |format|
      format.html {
      }
      format.js {
        html = render_to_string :partial => 'admin/events/events', layout: false, :locals => {:events => @events}
        html_footer = render_to_string :partial => 'admin/events/footer', layout: false, :locals => {:events => @events}
        render :json => {:success => true, :html => html, :footer => html_footer}
      }
    end
  end

  def new
    @event=@current_client.events.new
    @address=@event.build_address
    @promo_reps=@current_client.users.promo_representatives
  end

  def create
    @promo_reps=@current_client.users.promo_representatives
    @event=@current_client.events.new(event_params)
    @event.address.city = event_params[:address_attributes][:city] unless event_params[:address_attributes][:formatted_address].blank?
    user_ids=params[:event][:user_ids].reject(&:blank?).map(&:to_i)
    if event_params[:group_id].blank? and user_ids.blank?
      flash[:error]= "Either Direct Sourced or Group should be selected"
      render :new
      return
    end
    @event.creator= current_user
    user_ids.each do |user_id|
      user=User.find(user_id)
      @event.user_events.new(user_id: user_id, token: SecureRandom.hex[0, 6], status: :accepted)
    end
    unless params[:event][:group_id].blank?
      group=Group.find(params[:event][:group_id])
      group.users.each do |user|
        next if user_ids.include? user.id
        @event.user_events.new(user_id: user.id, token: SecureRandom.hex[0, 6], category: :promo_group)
      end
    end
    if @event.save
      @event.start_time = Time.find_zone(@event.address.time_zone).strptime(event_params[:start_time], '%m/%d/%Y %I:%M %p') unless event_params[:start_time].blank?
      @event.end_time = Time.find_zone(@event.address.time_zone).strptime(event_params[:end_time], '%m/%d/%Y %I:%M %p') unless event_params[:end_time].blank?
      @event.save
      EventJob.perform_later('event', @event, @event.user_ids)
      redirect_to admin_events_path
    else
      flash[:error]=@event.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def edit
    @event=Event.find(params[:id])
    @address=@event.address
    @promo_reps=@current_client.users.promo_representatives
  end

  def show
    @event = Event.find(params[:id])
  end
  def update
    reps = []
    group_email=false
    rep_email=false
    @event=Event.find(params[:id])
    user_ids=params[:event][:user_ids].reject(&:blank?).map(&:to_i)
    if event_params[:group_id].blank? and user_ids.blank?
      flash[:error]= "Either Direct Sourced or Group should be selected"
      redirect_to :back
      return
    end
    @event.assign_attributes(event_params)
    if @event.valid?
      if @event.address.city_changed? and params[:selected]=="false"
        @event.address.city = event_params[:address_attributes][:city]
        @event.address.update(address_1: nil,state: nil ,country: nil ,formatted_address: nil,zip: nil,longitude: nil,latitude: nil)
      end
      if @event.group_id_changed?
        group_email=true
        group=Group.find(@event.group_id_was)
        group.users.each do |user|
          @event.user_events.where(:user_id => user.id).first.delete if @event.user_events.where(:user_id => user.id).exists?
        end
        @event.group.users.each do |user|
          next if user_ids.include? user.id
          @event.user_events.new(user_id: user.id, token: SecureRandom.hex[0, 6], category: :promo_group)
        end
      end
      rep_ids=@event.user_events.where(:category => 0).map(&:user_id).reject(&:blank?)
      new_rep_ids=user_ids
      unless (new_rep_ids & rep_ids).empty?
        unless new_rep_ids.nil?
          delete_users=rep_ids-(new_rep_ids)
          delete_users.each do |del_user|
            @event.user_events.where(user_id: del_user).first.delete
          end
          create_users=new_rep_ids-delete_users
          rep_email=true if create_users.any?
          create_users.each do |user_id|
            if @event.user_events.where(:category => 0).collect { |c| c[:user_id] }.exclude? user_id
              # next if @event.group_id and @event.group.user_ids.include? user_id
              rep=User.find(user_id)
              reps << rep
              @event.user_events.new(user_id: user_id, token: SecureRandom.hex[0, 6], status: :accepted)
            end
          end
        end
      end
      @event.save!
      @event.start_time = Time.find_zone(@event.address.time_zone).strptime(event_params[:start_time], '%m/%d/%Y %I:%M %p') unless event_params[:start_time].blank?
      @event.end_time = Time.find_zone(@event.address.time_zone).strptime(event_params[:end_time], '%m/%d/%Y %I:%M %p') unless event_params[:end_time].blank?
      @event.save
      if group_email
        EventJob.perform_later('event', @event, @event.group.user_ids)
      end
      if rep_email
        EventJob.perform_later('event', @event, reps)
      end
      redirect_to admin_events_path
    else
      flash[:error]=@event.errors.full_messages.join(', ')
      redirect_to :back
    end

  end
  private
  def event_params
    params.require(:event).permit(:name, :event_type_id,:notes, :start_time, :end_time, :brand_id, :user_ids, :group_id, :max_users, :pay, :area, address_attributes: [:address_1, :city, :state, :zip, :country, :latitude, :longitude, :formatted_address ,:time_zone])
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::ApiApplicationController


  def index
    @events = current_user.events.active.active_events.includes(:user_events).where(:user_events => {:user_id => current_user.id})
  end

  def update
    @event=current_user.events.find(params[:id])
    @user_event=UserEvent.where(user_id: current_user.id, event_id: @event.id, status: :accepted).first
    # if @event.promo_rep?
    #   @user_event=UserEvent.where(user_id: current_user.id, event_id: @event.id, :category => 'promo_rep').first
    # elsif @event.promo_group?
    #   @user_event=UserEvent.where(user_id: current_user.id, event_id: @event.id, :category => 'promo_group').first
    # end

    unless user_event_params[:check_in].nil?
      if user_event_params[:check_in] < (@event.start_time-1.hour)
        render 'global/error', :locals => {:code => 701, :message => 'you can checkin only before an hour'}
        return
      end
      if current_user.events.active.checkedin_events.includes(:user_events).where(:user_events => {:user_id => current_user.id}).size>0
        render 'global/error', :locals => {:code => 701, :message => 'can check in only one event at a time'}
        return
      end
    end
    if @user_event.update_attributes(user_event_params)
      if (@event.end_time+1.hour).to_i  < Time.now.utc.to_i and !user_event_params[:check_out].nil?
        @user_event.update_attribute(:check_out,@event.end_time + 1.hour)
      end
      if params[:user_event][:images].nil?
        render :show
      else
        success, error, images= add_images(params[:user_event][:images], @user_event)
        if success
          @user_event.update_attribute(:images, images) unless images.nil?
          render :show
        else
          render 'global/error', :locals => {:code => 701, :message => error}
          return
        end
      end
    else
      render 'global/error', :locals => {:code => 701, :message => @user_event.errors.full_messages.join(', ')}
    end
  end

  def active
    @events = current_user.events.active.checkedin_events.includes(:user_events).where(:user_events => {:user_id => current_user.id})
    render :index
  end

  def expired
    @events = current_user.events.active.expired_events.includes(:user_events).where(:user_events => {:user_id => current_user.id}).order('end_time desc')
    render :index
  end

  private


  def user_event_params
    params.require(:user_event).permit(:notes, :total_expense, :check_in, :check_out, :images, :follow_up, :recommended, :recap,:attendance, :sample)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def show
    @event=Event.find(params[:id])
    if params[:token]
      user_event=UserEvent.find_by(token: params[:token])
      if @event.end_time < Time.now.utc
        @msg= "Event expired"
      else
        if user_event.promo_group?
          if params[:status]=="accept"
            if user_event.accepted?
              @msg= "Event accepted already!"
            else
              if @event.max_users > @event.user_events.where(:status => UserEvent::statuses[:accepted], :category => UserEvent::categories[:promo_group]).count
                user_event.status = :accepted
                user_event.save
                @msg= "Event accepted successfully!"
              else
                @msg= "Sorry!!Event reached max no of users!"
              end
            end

          elsif params[:status]=="decline"
            user_event.status = :declined
            user_event.save
            @msg= "Event declined sucessfully"
          end
        end
      end
    end
  end

end

app/controllers/superadmin/events_controller.rb
class Superadmin::EventsController < Superadmin::SuperadminApplicationController


  def index
    @events = Event.active.order('updated_at desc')
    unless @events.kind_of?(Array)
      @events = @events.page(params[:page]).per(20)
    else
      @events = Kaminari.paginate_array(@events.uniq).page(params[:page]).per(20)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.update_attribute(:deleted, true)
    flash[:notice] = 'Event deleted Successfully'
    redirect_to superadmin_events_path
  end

end

app/views/admin/events/_events.slim
table.table#sort-data-table
  thead
    tr.active
      th ID
      th Event Name
      th Client Name
      th Event Type
      th Venue
      th Start Time
      th End Time
      th Brand
      th.text-center Actions
  tbody
    -if @events
      -@events.each do |event|
        tr
          td #{event.id}
          td #{event.name}
          td #{event.client.name}
          td #{event.event_type&.name}
          td #{event.address&.city}
          td #{((event.start_time)&.in_time_zone(event.address&.time_zone))&.strftime('%m/%d/%Y %I:%M %p')}
          td #{((event.end_time)&.in_time_zone(event.address&.time_zone))&.strftime('%m/%d/%Y %I:%M %p')}
          td #{event.brand&.name}
          td.text-center
            -if request.path.include? 'superadmin'
              = link_to superadmin_event_path(:id => event.id), :data => {:confirm => 'Are you sure, you want to delete?'}, :title => 'Delete', :method => :delete, class: 'btn btn-sm btn-danger' do
                i.glyphicon.glyphicon-trash
            -else
              = link_to edit_admin_event_path(event), class: 'btn-sm  btn-icon btn btn-rounded btn-warning' do
                i.icmn-pencil4
    -else
      td
        | No events

app/views/admin/events/_footer.slim
-unless @events.nil?
  = paginate @events

app/views/admin/events/_form.html.slim
div
  = form_for [:admin, @event] do |f|
    .panel
      #breadcrumb-align
        ul.list-unstyled.breadcrumb
          li
            a href='#{admin_events_path}'   Events
          li
            span #{@event.new_record? ? 'Create ' : 'Edit '} Event
    .panel.panel-with-borders
      .panel-heading
        h4.panel-title #{@event.new_record? ? 'Create ' : 'Edit '} Event
      .panel-body
        =hidden_field_tag :selected
        =f.hidden_field :promo_category
        .form-group.row
          .col-md-12
            = f.label :name, 'Event Name'
            sup.text-danger *
            = f.text_field :name, class: 'name form-control', :autocomplete => true, required: true
        .form-group.row
          .col-md-6
            = f.label :type, 'Event Type'
            sup.text-danger *
            =select_tag 'event[event_type_id]', options_for_select(EventType.all.collect { |u| [u.name, u.id] }, selected_key = @event.event_type_id), {:class => 'form-control pointer selectpicker', required: true ,:include_blank=>'Nothing Selected'}
            .help-block.with-errors
          .col-md-6
            = f.label :brand, 'Brand Name'
            sup.text-danger *
            =select_tag 'event[brand_id]', options_for_select(@current_client.brands.active_brands.collect { |u| [u.name, u.id] }, selected_key = @event.brand_id), {:class => 'form-control pointer selectpicker', required: true,:include_blank=>'Nothing Selected'}
        .form-group.row
          .col-md-3
            = f.label :max_users, 'Promo Staff Needed'
            sup.text-danger *
            -if @event.max_users==0
              -value=1
            -else
              -value=@event.max_users
            = f.number_field :max_users, min: 1, class: 'form-control', required: true, :value => value
          .col-md-6
            = f.label :promo_reps, 'Direct Sourced'
            sup.text-danger
            -selected=@event.user_events.where(:category => 0).collect { |c| c[:user_id] }
            =f.select :user_ids, options_for_select(@promo_reps.collect { |u| [u.full_name, u.id] }, selected_key = selected), {}, {:multiple => true, :class => 'form-control selectpicker show-tick', 'data-live-search' => true}
            .help-block.with-errors
          .col-md-3
            = f.label :promo_groups, 'Promo Groups'
            sup.text-danger
            =f.select :group_id, options_for_select(@current_client.groups.collect { |u| [u.name, u.id] }, selected_key = @event.group_id), {}, {:class => 'form-control selectpicker show-tick pointer', :title => 'Select Group'}
            .help-block.with-errors

        .form-group.row
          .col-sm-6
            =f.label :start_time, 'Start Time'
            sup.text-danger *
            #start_time.input-group.date
              =f.text_field :start_time, class: 'form-control', required: true, value: ((@event.start_time)&.in_time_zone(@event.address&.time_zone))&.strftime('%m/%d/%Y %I:%M %p')
              span.input-group-addon.pointer
                i.icmn-calendar4
          .col-sm-6
            =f.label :end_time, 'End Time'
            sup.text-danger *
            #end_time.input-group.date
              =f.text_field :end_time, class: 'form-control', required: true, value: ((@event&.end_time)&.in_time_zone(@event.address&.time_zone))&.strftime('%m/%d/%Y %I:%M %p')
              span.input-group-addon.pointer
                i.icmn-calendar4
        .form-group.row
          .col-sm-12
            =f.label :area, 'Area'
            sup.text-danger *
            = f.text_field :area, class: 'form-control', required: true

        = f.fields_for :address do |addr|
          .form-group.row
            .col-md-12
              = f.label :city, 'Event Venue Address'
              sup.text-danger *
              .input-group
                = addr.text_field :city, class: 'city form-control ', :autocomplete => true, placeholder: "Please enter correct zip code or address", required: true
                span.input-group-addon.btn-primary.pointer
                  i.fa.fa-map-marker
                =addr.hidden_field :state, class: 'state'
                =addr.hidden_field :country, class: 'country'
                =addr.hidden_field :zip, class: 'zip'
                =addr.hidden_field :formatted_address, class: 'formatted_address'
                =addr.hidden_field :latitude, class: 'latitude'
                =addr.hidden_field :longitude, class: 'longitude'
        .form-group.row
          .col-sm-12
            =f.label :notes, 'Notes'
            = f.text_area :notes, class: 'form-control', rows: 5
      .panel-footer
        .form-group.row
          .col-md-9.col-md-offset-5
            =f.submit 'Submit', class: 'button btn width-150 btn-primary'
            '
            a.button.btn.btn-default href="#{admin_events_path}" Cancel
.padding-bottom-25

app/views/admin/events/edit.html.slim
.clearfix
  =render 'form'

app/views/admin/events/index.html.slim
div
  .panel
    .panel-heading
      .pull-right
        =link_to "Create Event", new_admin_event_path, class: 'btn btn-info'
      /= link_to new_admin_event_path, class: "btn btn-info" do
      /  i.left-menu-link-icon
      /  |&nbsp;Event
      .col-sm-5.pull-right
        .fieldwrapper
          =form_tag admin_events_path, method: :get, class: 'search_form' do
            .right.hidden-md-down.margin-left-20
              .search-block
                .form-input-icon.form-input-icon-right.disable
                  i.glyphicon.glyphicon-search
                  =hidden_field_tag 'search_type'
                  =hidden_field_tag 'promo_id'
                  =text_field_tag "search", nil, placeholder: "Reps or Groups", class: 'form-control form-control-sm form-control-rounded field search_rep', :id => 'Postcode'

      h3 Events List
    .panel-body
      #events
        =render partial: 'admin/events/events', :locals => {:events => @events}
      .row
        .col-md-12
          small
            /.text-inline.text-danger *
            .text-inline Times are in the respective location's timezone
      .row
        .col-md-12
          small
            /.text-inline.text-danger #
            .text-inline Times are in #{Time.zone.to_s} Timezone
      .pull-right
        #events-footer
          = render partial: 'admin/events/footer', :locals => {:events => @events}
      - if @events.count>=5
        .padding-35
.padding-bottom-25

app/views/admin/events/new.html.slim
.clearfix
  =render 'form'

app/views/admin/events/show.html.slim
section.page-content
  #load_images
  .page-content-inner
    /! Pricing Tables
    .panel
      .panel-heading
        h3 #{@event.name}
      .panel-body
        .margin-bottom-50
          .invoice-block
            h4 #{@event.event_type&.name}
            .row
              .col-md-6
                address
                  | Timings:       #{((@event.start_time).in_time_zone(@event.address.time_zone))&.strftime('%m/%d/%Y %I:%M %p')} - #{((@event.end_time).in_time_zone(@event.address.time_zone))&.strftime('%m/%d/%Y %I:%M %p')}
                -if @event.address&.formatted_address.blank?
                  -address = @event.address&.city
                -else
                  -address = @event.address&.formatted_address
                address
                  | Venue:         #{address}
                address
                  | Payment/hr :      #{(get_amount(@event))}

                  br/
                  br/
              .col-md-6.text-right
                address
                  |  Brand :    #{@event.brand&.name}
                address
                  | Unit cost: $ #{@event.brand&.unit_cost}

            .table-responsive
              table.table.table-hover.text-right
                thead
                  tr
                    th Id
                    th Rep
                    th Attendance
                    th Sample
                    th Product Cost
                    th Expenses
                    th Hours
                    th Pay
                    th Recommended
                    th Check In
                    th Check out
                    th Images
                    th.text-center Actions

                tbody
                  -@event.user_events.where(:status => UserEvent::statuses[:accepted]).each_with_index do |uv, index|

                    tr
                      td.text-left #{uv.user.id}
                      td.text-left #{uv.user.full_name}
                      -if uv.recap==true
                        td.text-left #{uv.attendance}
                      -else
                        td.text-left
                      -if uv.recap==true
                        td.text-left #{uv.sample}
                      -else
                        td.text-left
                      -if uv.recap==true
                        td.text-left #{number_with_precision((@event.brand&.unit_cost||0)*((uv&.sample)||0).round, precision: 1,  strip_insignificant_zeros: true)}
                      -else
                        td.text-left
                      td.text-left #{uv.total_expense}
                      -if !uv.check_in.nil? and !uv.check_out.nil?
                        -hour=time_diff(uv.check_out, uv.check_in)
                        td.text-left #{hour}
                        td.text-left #{hour*(get_amount(@event))}
                      -else
                        td.text-left
                        td.text-left
                      td.text-left
                        -if uv.recommended==true
                          p.highlight Yes
                        -elsif uv.recommended==false
                          p.highlight No
                      td.text-left #{uv.check_in&.strftime('%m/%d/%Y %I:%M %p')}

                      td.text-left #{uv.check_out&.strftime('%m/%d/%Y %I:%M %p')}

                      td.text-left
                        -if uv.images&.size==0

                          p N/A
                        -else
                          a class="images" href= images_admin_dashboard_index_path(:user_event=> uv.id)  Show
                      td.text-center
                        = link_to edit_admin_event_user_event_path(:event_id => @event.id, :id => uv.id), class: 'btn-sm  btn-icon btn btn-rounded btn-warning' do
                          i.icmn-pencil4
        .row
          .col-md-12
            small
              /.text-inline.text-danger *
              .text-inline Times are in the respective location's timezone
        .row
          .col-md-12
            small
              /.text-inline.text-danger #
              .text-inline Times are in #{Time.zone.to_s} Timezone
.padding-15