config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions", invitations: "invitations"}
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  root 'homes#index'
  resources :homes
  resources :events
  namespace :superadmin do
    resources :event_types
    resources :events ,:only=>[:index ,:destroy]
    resources :clients do
      delete :remove_brand
      get :impersonate
      resources :users do
        get :resend_invitation
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :groups
    resources :events
    resources :brands
  end
  namespace :admin do
    get '/login_as_master' => 'admin_application#login_as_master'
    resources :dashboard do
      collection do
        get "images"
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :events do
      resources :user_events do
        delete :delete_image
      end
    end
    resources :groups
    resources :clients do
      collection do
        get :reps_and_groups
      end
    end
  end
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :contacts
      resources :events do
        collection do
          get :active
          get :expired
        end
      end
    end
  end
end

app/views/layouts/admin/_side_bar.slim
nav.left-menu left-menu=""
  .logo-container
    a.logo href=''
      img alt=("Promo Tracks") src=image_url("logo.png")
  .left-menu-inner.scroll-pane.col-md-10
    ul.left-menu-list.left-menu-list-root.list-unstyled
      li class="#{active_class(admin_dashboard_index_path)}"
        a.left-menu-link href=admin_dashboard_index_path
          i.left-menu-link-icon.fa.fa.fa-tachometer
          | Dashboard
      li class="#{active_class(admin_events_path)}"
        a.left-menu-link href=admin_events_path
          i.left-menu-link-icon.icmn-calendar
          | Events
      li class="#{active_class(admin_promo_reps_path)}"
        a.left-menu-link href=admin_promo_reps_path
          i.left-menu-link-icon.icmn-users
          | Direct Sourced
      li.left-menu-list class="#{active_class(admin_groups_path)}"
        a.left-menu-link href=admin_groups_path
          i.left-menu-link-icon.icmn-users4
          | Promo Groups

      li#top-menu1
        nav.top-menu.csm-menu
          .menu-icon-container.hidden-md-up
            .animate-menu-button.left-menu-toggle
              div
          .menu
            .menu-user-block
              .dropdown.dropdown-avatar
                a.dropdown-toggle#user-logo aria-expanded="false" data-toggle="dropdown" data-no-turbolink="true" href=("javascript: void(0);")
                  span.avatar href="javascript:void(0);"
                    -image=current_user.image.blank? ? "default-user.jpg" : current_user.image.url
                    = image_tag image, alt: "Image"
                  .dropdown style="bottom:10px;"
                ul.dropdown-menu.dropdown-menu-right aria-labelledby="" role="menu"
                  .dropdown-item
                    -if Client.where(:admin_id => current_user.id).exists?
                      li
                        =link_to edit_admin_client_path(Client.where(:admin_id => current_user.id).first)
                          i.dropdown-icon.fa.fa-user
                          |&nbsp; #{current_user.first_name}
                      .dropdown-divider
                      -if @current_slave_user
                        li
                          = link_to admin_login_as_master_path, data: {confirm: "Are you sure?"}, title: 'Back to Super Admin'
                            i.dropdown-icon.icmn-enter
                            |Back to SuperAdmin
                        .dropdown-divider
                    li
                      = link_to destroy_user_session_path, data: {confirm: "Are you sure?"}, title: 'Logout', :method => :delete
                        i.dropdown-icon.icmn-exit
                        | Logout

app/views/layouts/admin/_top_bar.slim
nav.top-menu
  .menu-icon-container.hidden-md-up
    .animate-menu-button.left-menu-toggle
      div
  /!
  .menu
    .menu-user-block
      .dropdown.dropdown-avatar
        a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href=("javascript: void(0);")
          span.avatar href="javascript:void(0);"
            -image=current_user.image.blank? ? "default-user.jpg" : current_user.image.url
            = image_tag image, alt: "Image"
          .dropdown#user-name-align style="bottom:5px;"
        ul.dropdown-menu.dropdown-menu-right aria-labelledby="" role="menu"
          .dropdown-item
            -if Client.where(:admin_id => current_user.id).exists?
              li
                =link_to edit_admin_client_path(Client.where(:admin_id => current_user.id).first)
                  i.dropdown-icon.fa.fa-user
                  |Profile
            .dropdown-divider
            -if @current_slave_user
              li
              = link_to admin_login_as_master_path, data: {confirm: "Are you sure?"}, title: 'Back to Super Admin'
                i.dropdown-icon.icmn-enter
                |Back to SuperAdmin
            .dropdown-divider
            li
              = link_to destroy_user_session_path, data: {confirm: "Are you sure?"}, title: 'Logout', :method => :delete
                i.dropdown-icon.icmn-exit
                | Logout

app/views/layouts/admin/application.html.slim
doctype html
html
  head
    title PromoTracks
    = favicon_link_tag image_path('icons/favicon-20.ico')
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body.theme-default.menu-top.menu-static
    -if flash.present?
      =render 'layouts/flash_msg_template'
    =render partial: 'layouts/admin/side_bar'
    /=render partial: 'layouts/admin/top_bar'
    section.page-content
      section.page-content-inner
      = yield
  =render partial: 'layouts/superadmin/footer'