config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions", invitations: "invitations"}
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  root 'homes#index'
  resources :homes
  resources :events
  namespace :superadmin do
    resources :event_types
    resources :events ,:only=>[:index ,:destroy]
    resources :clients do
      delete :remove_brand
      get :impersonate
      resources :users do
        get :resend_invitation
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :groups
    resources :events
    resources :brands
  end
  namespace :admin do
    get '/login_as_master' => 'admin_application#login_as_master'
    resources :dashboard do
      collection do
        get "images"
      end
    end
    resources :promo_reps do
      get :resend
    end
    resources :events do
      resources :user_events do
        delete :delete_image
      end
    end
    resources :groups
    resources :clients do
      collection do
        get :reps_and_groups
      end
    end
  end
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :contacts
      resources :events do
        collection do
          get :active
          get :expired
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_token_authenticatable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, password_length: 5..128, :invite_for => 2.weeks
  belongs_to :event
  belongs_to :group
  has_many :user_events
  has_many :events, :through => :user_events
  has_many :brands
  has_many :group_members
  has_many :groups ,:through => :group_members
  has_and_belongs_to_many :clients , join_table: :clients_users
  accepts_nested_attributes_for :clients, reject_if: :all_blank, allow_destroy: true
  mount_uploader :image, ImageUploader

  enum role: [:promo_rep, :super_admin, :client_admin]


  def full_name
    "#{first_name} #{last_name}"
  end

  def self.active_users
    self.where(deleted: false)
  end

  def self.group_members
    promo_rep.where(:group_id => nil).order('first_name')
  end

  def self.promo_representatives
    where(role: 'promo_rep').order('first_name')
  end
end

app/controllers/superadmin/clients_controller.rb
class Superadmin::ClientsController < Superadmin::SuperadminApplicationController


  def index
    @clients=Client.all.page(params[:page]).per(20)
  end

  def new
    @client=Client.new
    @admin=@client.users.new
    @brands= @client.brands.build
  end

  def create
    @client=Client.new(client_params)
    if client_params[:brands_attributes].nil?
      flash[:error]="Add Atleast one brand"
      redirect_to :back
      return
    end
    @client.users << @client.admin
    if @client.save
      redirect_to superadmin_clients_path
    else
      flash[:error]=@client.errors.full_messages.join(',')
      redirect_to :back
    end
  end

  def edit
    @client=Client.find(params[:id])
    @admin=@client.admin
    @brands=@client.brands
  end

  def update
    @client=Client.find(params[:id])
    if client_params[:brands_attributes].nil?
      flash[:error]="Add Atleast one brand"
      redirect_to :back
      return
    end
    client_call_params= client_params
    if client_params[:admin_attributes][:password].empty?
      client_call_params = client_update_params
    end
    if @client.update_attributes(client_call_params)
      redirect_to superadmin_clients_path
    else
      flash[:error]=@client.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def impersonate
    client = Client.find(params[:client_id])
    slave_user = User.find(params[:user_id])
    if slave_user
      session[:slave_user_id] = slave_user.id
      session[:role] = 'super_admin'
      redirect_to admin_dashboard_index_path, :notice => "Logged in as #{slave_user.full_name}"
    else
      flash[:notice] = 'Sorry! You cannot login as this user'
      redirect_back fallback_location: superadmin_clients_path
    end

  end


  def remove_brand
    client = Client.find(params[:client_id])
    brand=client.brands.find(params[:id])
    if Event.where(:brand_id => brand.id).exists?
      msg= "Unable to delete, since you have active events for this brand!"
    else
      brand.destroy
    end

    render json: {success: :true, :message => msg}
  end

  private

  def client_params
    params.require(:client).permit(:name, :phone, :payment,:brand_ids, admin_attributes: [:id, :first_name, :last_name, :password, :password_confirmation, :email, :role, :image], brands_attributes: [:id, :name, :unit_cost])
  end

  def client_update_params
    params.require(:client).permit(:name, :phone, :payment,:brand_ids, admin_attributes: [:id, :first_name, :last_name, :email, :role, :client_id, :image], brands_attributes: [:id, :name, :unit_cost])
  end


end

app/controllers/superadmin/event_types_controller.rb
class Superadmin::EventTypesController < Superadmin::SuperadminApplicationController


  def index
    @event_types=EventType.all.page(params[:page]).per(20)
  end


  def new
    @event_type=EventType.new
  end

  def create
    @event_type=EventType.new(event_type_params)
    if @event_type.save
      redirect_to superadmin_event_types_path
    else
      flash[:error]=@event_type.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @event_type=EventType.find(params[:id])
  end

  def update
    @event_type=EventType.find(params[:id])
    if @event_type.update_attributes(event_type_params)
      redirect_to superadmin_event_types_path
    else
      flash[:error]=@event_type.errors.full_messages.join(', ')
      render :edit
    end
  end

  private
  def event_type_params
    params.require(:event_type).permit(:name)
  end

end

app/controllers/superadmin/events_controller.rb
class Superadmin::EventsController < Superadmin::SuperadminApplicationController


  def index
    @events = Event.active.order('updated_at desc')
    unless @events.kind_of?(Array)
      @events = @events.page(params[:page]).per(20)
    else
      @events = Kaminari.paginate_array(@events.uniq).page(params[:page]).per(20)
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.update_attribute(:deleted, true)
    flash[:notice] = 'Event deleted Successfully'
    redirect_to superadmin_events_path
  end

end

app/controllers/superadmin/groups_controller.rb
class Superadmin::GroupsController < Superadmin::SuperadminApplicationController


  def index
    @groups=Group.all.page(params[:page]).per(10)
  end

  def new
    @group=Group.new
    @promo_reps=User.promo_rep
  end

  def create
    @group=Group.new(group_params)
    @group.user_ids= params[:group][:user_ids].reject(&:blank?)
    @group.save
    redirect_to superadmin_groups_path
  end

  def edit
    @group=Group.find(params[:id])
    @promo_reps=User.promo_rep
  end

  def update
    @group=Group.find(params[:id])
    @group.assign_attributes(group_params)
    if @group.valid?
      @group.user_ids = params[:group][:user_ids].reject(&:blank?)
      @group.save
      redirect_to superadmin_groups_path
    else
      flash[:error]=@group.errors.full_messages.join(', ')
      redirect_to :back
    end
  end


  private
  def group_params
    params.require(:group,).permit(:name)
  end
end

app/controllers/superadmin/promo_reps_controller.rb
require 'platform/email_helper'
class Superadmin::PromoRepsController < Superadmin::SuperadminApplicationController
  include EmailHelper

  def index
    @promo_reps=User.where(role: 'promo_rep').order('first_name').collect { |u| u }
    unless @promo_reps.kind_of?(Array)
      @promo_reps = @promo_reps.page(params[:page]).per(10)
    else
      @promo_reps = Kaminari.paginate_array(@promo_reps.uniq).page(params[:page]).per(10)
    end
  end

  def new
    @promo_rep=User.new
  end

  def create
    pro_rep=User.new(user_params)
    pro_rep.password = generate_token
    pro_rep.token = generate_token
    if pro_rep.save
      UserJob.perform_later('add_rep', pro_rep)
      redirect_to superadmin_promo_reps_path
    else
      flash[:error]=pro_rep.errors.full_messages.join(', ')
      redirect_to :back
    end
  end


  def edit
    @promo_rep=User.find(params[:id])
  end

  def update
    @promo_rep=User.find(params[:id])
    if @promo_rep.update_attributes(user_params)
      redirect_to superadmin_promo_reps_path
    else
      flash[:error]=@promo_rep.errors.full_messages.join(', ')
      redirect_to :back
    end
  end


  def resend
    @promo_rep=User.find(params[:promo_rep_id])
    @promo_rep.update_attribute(:token, generate_token)
    UserJob.perform_later('resend_token', @promo_rep)
    flash[:notice] = "Password sent!"
    redirect_to superadmin_promo_reps_path
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role, :area ,:phone)
  end
end

app/controllers/superadmin/superadmin_application_controller.rb
module Superadmin
  class SuperadminApplicationController < ApplicationController
    protect_from_forgery with: :exception

    before_action :authenticate_user!

    layout 'superadmin/application'

    def authenticate_superadmin
      if current_user.super_admin? and ENV['superadmins'].split(',').include? current_user.email
        true
      end
    end

  end
end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::SuperadminApplicationController

  def index
    @client=Client.find(params[:client_id])
    @users=@client.users.active_users.client_admin
  end

  def new
    @client=Client.find(params[:client_id])
    @user=@client.users.new
  end

  def create
    @client=Client.find(params[:client_id])
    user = User.find_by_email(params[:user][:email])
    if user.nil?
      user=User.new(user_params)
      user.invite!
      @client.users << user
      @client.save
      flash[:notice]= "Admin Invited Sucessfully"
      redirect_to superadmin_client_users_path
    elsif user.deleted
      user.deleted = false
      user.update_attributes(user_params)
      user.invite!
      unless @client.user_ids.include? user.id
        @client.users << user
        @client.save
      end
      flash[:notice]= "Admin Invited Sucessfully"
      redirect_to superadmin_client_users_path
    else
      flash[:error]= "User Already Exists"
      redirect_to :back
    end
  end

  def resend_invitation
    @user = User.find(params[:user_id])
    @user.invite!
    flash[:notice] = 'Invitation sent!'
    redirect_to superadmin_client_users_path
  end

  def destroy
    @client=Client.find(params[:client_id])
    @user = User.find(params[:id])
    @users=@client.users.active_users.client_admin
    if @users.size>1
      @client.users.delete(@user)
      @user.update_attribute(:deleted , true)
      @client.admin=@users.first
      @client.save
      flash[:notice] = 'Admin deleted successfully!'
      redirect_to superadmin_client_users_path
    else
      flash[:notice] = 'Their should atleast one active admin'
      redirect_to :back
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :role)
  end


end

app/views/superadmin/users/index.html.slim
.col-md-offset-1.col-md-10
  .panel
    .container#breadcrumb-align
      ul.list-unstyled.breadcrumb
        li
          a href='#{superadmin_clients_path}'   Clients
        li
          span Admins
  .panel
    .panel-heading
      .pull-right
        =link_to "Invite Admin", new_superadmin_client_user_path, class: 'btn btn-info btn-sm'
      h4 Admins
    .panel-body
      table.table.table-striped
        thead
          tr
            th.col-md-2 ID
            th.col-md-3 Name
            th.col-md-5 Email
            th.col-md-2.text-center Action
        tbody
          -@users.each do |user|
            tr
              td.col-md-2 #{user.id}
              td.col-md-3 #{user.full_name}
              td.col-md-5 #{user.email}
              td.col-md-2.text-center
                -unless @client.admin == user
                  = link_to superadmin_client_user_resend_invitation_path(@client.id,user.id), class: 'btn-sm  btn-icon btn btn-rounded btn-primary' ,:data => {:toggle => 'tooltip', :placement => 'top'}, :title => "resend invitation" do
                    i.icmn-envelop5
                '
                = link_to superadmin_client_user_path(@client.id,user.id), :data => {:confirm => 'Are you sure, you want to delete?'}, :title => 'Delete', :method => :delete, class: 'btn btn-sm btn-danger' do
                  i.glyphicon.glyphicon-trash

app/views/superadmin/users/new.html.slim
.col-md-offset-3.col-md-6
  = form_for [:superadmin, :client, @user] do |f|
    .panel
      .container#breadcrumb-align
        ul.list-unstyled.breadcrumb
          li
            a href='#{superadmin_clients_path}'   Clients
          li
            a href='#{superadmin_client_users_path}'   Admins
          li
            span New Admin
    .panel.panel-with-borders
      .panel-heading
        h2.panel-title #{@user.new_record? ? 'New ' : 'Edit '} Admin
      .panel-body
        .form-group.row
          .col-md-6
            = f.label :first_name
            sup.text-danger *
            =f.hidden_field :role, :value => :client_admin
            = f.text_field :first_name, class: 'name form-control ', required: true
          .col-md-6
            = f.label :last_name
            sup.text-danger *
            = f.text_field :last_name, class: 'name form-control ', required: true
        .form-group.row
          .col-md-12
            = f.label :email
            sup.text-danger *
            = f.email_field :email, class: 'form-control ', required: true
      /.form-group.row
          .col-md-6
            = f.label :password
            sup.text-danger *
            = f.password_field :password, class: 'form-control ', required: true
          .col-md-6
            = f.label :password_confirmation
            sup.text-danger *
            = f.password_field :password_confirmation, class: 'form-control ', required: true

      .panel-footer
        .text-right
          =f.submit 'Invite', class: 'btn btn-success'
          '
          a.btn.btn-danger href="#{superadmin_client_users_path}" Cancel